---
- name: install redis packages
  package:
    name: '{{ redis_packages }}'
    state: present

- name: set up redis directories
  file:
    path: '{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.user }}'
    group: '{{ item.group }}'
  with_items: '{{ redis_directories }}'

- name: generate redis config
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart redis

- name: enable redis service
  service:
    name: redis
    enabled: true
    state: started

- name: flush_handlers
  meta: flush_handlers
