---
- name: install redis packages
  package:
    name: '{{ redis_packages }}'
    state: present

- name: enable redis service
  service:
    name: redis
    enabled: true

- name: generate redis config
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart redis
