---
- name: OpenBSD homeserver setup
  hosts: homeserver
  vars_files:
    - defaults.yml
    - secrets.yml
    - vars.yml
    - extrapolate.yml
    - overrides.yml
  pre_tasks:
    - name: create homelab group
      group:
        name: _homelab
    - name: create homelab user
      user:
        name: _homelab
        group: _homelab
        comment: OBSD HomeLab user
        home: /var/homelab
        password: '*************'
        password_lock: true
        shell: /bin/ksh
    - name: remove homelab ssh directory
      file:
        state: absent
        path: /var/homelab/.ssh
  roles:
    - {role: lego, tags: ['lego']}
    - {role: syslog, tags: ['syslog']}
    - {role: openldap, tags: ['openldap']}
    - {role: ldap_data, tags: ['ldap_data']}
    - {role: saslauth, tags: ['saslauth']}
    - {role: nginx, tags: ['nginx']}
    - {role: redis, tags: ['redis']}
    - {role: php, tags: ['php']}
    - {role: postgresql, tags: ['postgresql']}
    - {role: mariadb, tags: ['mariadb']}
    - {role: vaultwarden, tags: ['vaultwarden']}
    - {role: monica, tags: ['monica']}
    - {role: calibre_web, tags: ['calibre_web']}
    # - {role: redmine, tags: ['redmine']}
    # - {role: freshrss, tags: ['freshrss']}
    # - {role: phpldapadmin, tags: ['phpldapadmin']}
    # - {role: nextcloud, tags:['nextcloud']}
    # - {role: znc, tags:['znc']}
    # - {role: gitolite, tags: ['gitolite']}
    # - {role: calibre, tags: ['calibre']}
    # - {role: gitea, tags: ['gitea']}
    # - {role: synapse, tags: ['synapse']}
    # - {role: dendrite, tags: ['dendrite']}
    # - {role: pf, tags: ['pf']}
