---
- name: OpenBSD homeserver setup
  hosts: homeserver
  vars_files:
    - defaults.yml
    - vars.yml
    - extrapolate.yml
    - overrides.yml
  roles:
    - {role: nginx}
    #- {role: acme}
    - {role: openldap}
    - {role: saslauthd}
    - {role: postgresql}
    - {role: php}
    - {role: redis}
    # - {role: nextcloud}
    # - {role: clamav}
    # - {role: davical}
    # - {role: znc}
    # - {role: redmine}
    # - {role: calibre}
    # - {role: calibre_web}
    # - {role: gitea}
    # - {role: vaultwarden}
    # - {role: synapse}
    # - {role: dendrite}
    #- {role: pf}
    #- {role: syslog}
