---
- name: get ldap reader password hash
  shell: |
    set -o pipefail
    echo '{{ ldap_pass }}' | encrypt
  register: _ldap_reader_hash
  changed_when: false

- name: add ldap reader account
  ldap_entry:
    dn: 'cn=ldap,ou=Users,{{ openldap_base }}'
    objectClass:
      -inetOrgPerson
    attributes:
      cn: ldap
      sn: reader
      userPassword: '{CRYPT}{{ _ldap_reader_hash.stdout }}'
