---
- name: create acme-client.conf
  template:
    src: acme-client.conf.j2
    dest: /etc/acme-client.conf
    owner: root
    group: wheel
    mode: 0644

- name: generate acme certificates
  command: acme-client -vv "{{ domain }}"
  register: acme_client
  changed_when: acme_client.rc == 0
  failed_when: acme_client.rc != 0 and acme_client.rc != 2
  notify: restart nginx

- name: symlink site config
  file:
    src: "../sites-available/{{ domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
    owner: root
    group: wheel
    state: link
  notify: restart nginx

- name: flush_handlers
  meta: flush_handlers
