---
- name: create acme-client.conf
  template:
    src: acme-client.conf.j2
    dest: /etc/acme-client.conf
    owner: root
    group: wheel
    mode: 0644

- name: create daily.local
  file:
    path: /etc/daily.local
    state: touch
    owner: root
    group: wheel
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: generate daily certificate updating script
  template:
    src: daily.local.certs.j2
    dest: /etc/daily.local.certs
    owner: root
    group: wheel
    mode: '0644'

- name: ensure daily.local calls daily.cert
  lineinfile:
    path: /etc/daily.local
    regex: '^\. /etc/daily.local.certs$'
    line: '. /etc/daily.local.certs'

- name: generate acme certificates
  command: /bin/sh /etc/daily.local.certs
  register: acme_client
  changed_when: "'UPDATED' in acme_client.stderr"
  failed_when: "'ERROR' in acme_client.stderr"

- name: symlink site config
  file:
    src: "../sites-available/{{ domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
    owner: root
    group: wheel
    state: link
  notify: restart nginx

- name: flush_handlers
  meta: flush_handlers
