---
- name: add base domain
  ldap_entry:
    dn: '{{ ldap_base }}'
    objectClass:
      - dcObject
      - organization
    attributes:
      o: OBSD HomeLab
      dc: '{{ openldap_base_dc }}'

- name: add organizational units
  ldap_entry:
    dn: 'ou={{ item }},{{ ldap_base }}'
    objectClass:
      - organizationalUnit
    attributes:
      ou: '{{ item }}'
  with_items:
    - 'InternalUsers'
    - 'Users'
    - 'Groups'

- name: get ldap reader password hash
  shell: |
    set -o pipefail
    echo '{{ ldap_pass }}' | encrypt
  register: _ldap_reader_hash
  changed_when: false

- name: add ldap reader account
  ldap_entry:
    dn: 'uid=ldap,ou=InternalUsers,{{ ldap_base }}'
    objectClass:
      - inetOrgPerson
      - hlUser
    attributes:
      uid: ldap
      cn: ldap
      sn: reader
      mail: 'ldap@internal.{{ ldap_domain }}'
      userPassword: '{CRYPT}{{ _ldap_reader_hash.stdout }}'

- name: get admin password hash
  shell: |
    set -o pipefail
    echo '{{ admin_pass }}' | encrypt
  register: _ldap_admin_hash
  changed_when: false

- name: add admin account
  ldap_entry:
    dn: 'mail={{ admin_mail }},ou=Users,{{ ldap_base }}'
    objectClass:
      - inetOrgPerson
      - hlUser
    attributes:
      mail: '{{ admin_mail }}'
      cn: admin
      sn: homelab
      hlDefaultAllow: 'TRUE'
      userPassword: '{CRYPT}{{ _ldap_admin_hash.stdout }}'
