#!/bin/ksh

set -e

pname="$(basename "$0")"
USAGE="$(cat <<EOF
$pname : Change OpenLDAP admin password
usage:
    $pname [-b rounds] [-h]

EOF
)"

rounds=12

while getopts "b:h" opt
do
    case $opt in
        b) rounds="$OPTARG";;
        h) printf %s\\n "$USAGE"; exit;;
        ?) printf %s\\n "$USAGE"; exit 1;;
    esac
done

salt="\$2b\$${rounds}\$%.22s"

pass_hash=$(/usr/local/sbin/slappasswd -c "${salt}")

/usr/local/bin/ldapmodify -Y EXTERNAL -Q -H 'ldapi://%2ftmp%2fslapd.sock' <<EOF
dn: olcDatabase={0}config,cn=config
changeType: modify
replace: olcRootPW
olcRootPW: $pass_hash

dn: olcDatabase={1}mdb,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: $pass_hash
EOF
