---
- name: install mariadb packages
  package:
    name: "{{ mdb_packages }}"
    state: present

- name: set up mysql directories
  file:
    path: '{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
    owner: '{{ item.user }}'
    group: '{{ item.group }}'
  with_items: '{{ mdb_directories }}'

- name: initialize mysqld
  command: /usr/local/bin/mariadb-install-db
  args:
    creates: /var/mysql/ib_buffer_pool

- name: generate configuration
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart mariadb

- name: ensure mariadb is started
  service:
    name: mysqld
    enabled: true
    state: started

- name: flush_handlers
  meta: flush_handlers
