---
- name: Install vaultwarden packages
  ansible.builtin.package:
    name: '{{ vw_packages }}'
    state: present

- name: Generate vaultwarden config
  ansible.builtin.template:
    src: env.j2
    dest: /var/vaultwarden/.env
    owner: _vaultwarden
    group: _vaultwarden
    mode: '0640'
  notify: Restart vaultwarden

- name: Generate vaultwarden_ldap config
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/vaultwarden_ldap/config.toml
    owner: _vaultwarden
    group: _vaultwarden
    mode: '0640'
  notify: Restart vaultwarden_ldap

- name: Enable vaultwarden services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items: ['vaultwarden', 'vaultwarden_ldap']

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
