---
- name: install prosody packages
  ansible.builtin.package:
    name: '{{ prosody_packages }}'
    state: present

- name: create postgresql user
  community.general.postgresql_user:
    name: prosody
    password: '{{ prosody_db_pass }}'

- name: create postgresql databases
  community.general.postgresql_db:
    name: prosodyd
    owner: prosody
    encoding: UTF-8
    template: template0

- name: add prosody user to lego group
  ansible.builtin.user:
    name: _prosody
    append: true
    groups: _lego
    create_home: false

- name: create prosody global config
  ansible.builtin.template:
    src: prosody.cfg.lua.j2
    dest: /etc/prosody/prosody.cfg.lua
    owner: _prosody
    group: _prosody
    mode: '0640'
  notify: restart prosody

- name: create prosody domain config
  ansible.builtin.template:
    src: domain.cfg.lua.j2
    dest: '/etc/prosody/conf.d/{{ prosody_domain }}.cfg.lua'
    owner: _prosody
    group: _prosody
    mode: '0640'
  notify: restart prosody

- name: symlink certificates
  ansible.builtin.file:
    src: '/etc/ssl/{{ item }}'
    path: '/etc/prosody/certs/{{ item }}'
    state: link
    follow: false
    owner: _prosody
    group: _prosody
    mode: '0755'
  with_items:
    - homelab.crt
    - homelab.key

- name: enable prosody service
  ansible.builtin.service:
    name: prosody
    state: started
    enabled: true

- name: flush_handlers
  ansible.builtin.meta: flush_handlers
