---
- name: Restart vaultwarden
  ansible.builtin.service:
    name: vaultwarden
    state: restarted

- name: Restart vaultwarden_ldap
  ansible.builtin.service:
    name: vaultwarden_ldap
    state: restarted
