- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: generate acme certs
  command: acme-client {{ domain }}

- name: ocspcheck
  command: ocspcheck -N -o /etc/ssl/{{ domain }}.ocsp /etc/ssl/{{ domain }}.crt

- name: restart relayd
  service:
    name: relayd
    state: restarted
