---
redis_packages:
  - redis

# 250 MB in bytes
redis_maxmem: 262144000
redis_maxmem_policy: "allkeys-lfu"

redis_addrs: []

# TCP Port to listen on. Set to 0 to disable listening on a TCP socket.
redis_port: 6379

redis_protected: "no"

redis_socket_path: "/var/www/var/run/redis/redis.sock"
redis_socket_perm: "777"

redis_directories:
  - path: '/var/www/var/run/redis'
    user: _redis
    group: _redis
    mode: '0755'
