---

- name: include very minimalistic ksh goodies
  include: optional_ksh.yml
  when: base_ksh

- name: include very simple tmux config
  include: optional_tmux.yml
  when: base_tmux

- name: include simple hardened ssh config
  include: optional_ssh.yml
  when: base_ssh

- meta: flush_handlers
