- name: create /etc in www chroot
  file:
    path: /var/www/etc
    state: directory

- name: create ssh group with access
  group:
    name: ssh-access

- name: add users to ssh-access group
  user:
    name: '{{ item }}'
    groups: ssh-access
    append: yes
  with_items: '{{ [ admin_user ] + (ssh_users | default([])) }}'

- name: generate pf.conf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
  notify: reload pf

- name: generate sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd

- name: touch log files
  copy:
    content: ""
    dest: /var/log/{{ item }}
    force: no
    mode: 0640
  with_items: '{{ syslog_log_files }}'
  notify: reload syslog

- name: generate syslog configuration
  copy:
    src: syslog.conf
    dest: /etc/syslog.conf
  notify: reload syslog

- name: generate newsyslog configuration
  copy:
    src: newsyslog.conf
    dest: /etc/newsyslog.conf
  notify: newsyslog

- name: generate dhparams
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048
  args:
    creates: /etc/ssl/dhparam.pem

- name: set up permissions on /var/www/{tmp,run}
  file:
    path: /var/www/{{ item }}
    state: directory
    mode: 01775
    owner: www
    group: www
  with_items:
    - tmp
    - run

- name: set up permissions on /var/www/cache
  file:
    path: /var/www/cache
    state: directory
    mode: 0755
    owner: root
    group: daemon

- name: chown /var/www/logs
  file:
    path: /var/www/logs
    state: directory
    mode: 0750
    owner: www
    group: wheel

- name: create profile.d directory
  file:
    path: /etc/profile.d
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: copy shell files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: wheel
  with_items:
    - { src: ksh.kshrc, dest: /etc/ksh.kshrc }
    - { src: profile, dest: /etc/profile }
    - { src: polyglot/polyglot.sh, dest: /etc/profile.d/polyglot.sh }
    - { src: profile.d/aliases.sh, dest: /etc/profile.d/aliases.sh }
    - { src: profile.d/functions.sh, dest: /etc/profile.d/functions.sh }

