---

- name: copy tmux config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: wheel
  with_items:
    - { src: tmux.conf, dest: /etc/tmux.conf }

