---
- name: Install calibre-web packages
  ansible.builtin.package:
    name: '{{ cw_packages }}'
    state: present

- name: Create calibre-web directories
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: _calibre-web
    group: _calibre-web
    mode: '0755'
  with_items:
    - '/var/calibre/'
    - '/var/calibre/calibre-web'
    - '/var/calibre/.config'

- name: Create calibre-web-runner directories
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: _calibre-web-runner
    group: _calibre-web-runner
    mode: '0750'
  with_items:
    - /var/calibre/books
    - /var/calibre/.calibre-web
    - /var/calibre/.config/calibre

- name: Install calibre-web in virtualenv
  ansible.builtin.pip:
    virtualenv: /var/calibre/calibre-web
    virtualenv_site_packages: true
    name: 'calibreweb[ldap]'
  environment:
    CPPFLAGS: '-I/usr/local/include'
    LDFLAGS: '-L/usr/local/lib'
    HOME: /var/calibre/calibre-web
  become: true
  become_user: _calibre-web

- name: Install calibre-web launcher
  ansible.builtin.copy:
    src: calibre_web-launcher
    dest: /usr/local/libexec/calibre_web-launcher
    owner: root
    group: wheel
    mode: '0755'

- name: Create calibre-web rc script
  ansible.builtin.template:
    src: calibre_web.j2
    dest: /etc/rc.d/calibre_web
    owner: root
    group: wheel
    mode: '0755'

- name: Enable and start calibre-web service
  ansible.builtin.service:
    name: calibre_web
    enabled: true
    state: started

- name: Ensure /var/calibre/books has a calibre database
  ansible.builtin.command:
    cmd: /usr/local/bin/calibredb --with-library /var/calibre/books list
    creates: /var/calibre/books/metadata.db
  become: true
  become_user: _calibre-web-runner

- name: Update admin user  # noqa no-changed-when
  ansible.builtin.command: >
    sqlite3 /var/calibre/.calibre-web/app.db
    'UPDATE user SET
     name = "{{ cw_admin }}",
     email = "{{ cw_admin_mail }}",
     password = NULL
     WHERE id = 1;'
  become: true
  become_user: _calibre-web-runner

- name: Set config options in calibre-web sqlite db  # noqa no-changed-when
  ansible.builtin.command: >
    sqlite3 /var/calibre/.calibre-web/app.db
    'UPDATE settings SET
    mail_server = "{{ cw_smtp_host }}",
    mail_port = "{{ cw_smtp_port }}",
    mail_use_ssl = {{ 2 if cw_smtp_tls else 1 if cw_smtp_starttls else 0 }},
    mail_login = "{{ cw_smtp_user }}",
    mail_password = "{{ cw_smtp_pass }}",
    mail_from = "{{ cw_smtp_from }}",
    config_calibre_dir = "/var/calibre/books",
    config_login_type = 1,
    config_ldap_provider_url = "127.0.0.1",
    config_ldap_port = 389,
    config_ldap_authentication = 2,
    config_ldap_serv_username = "{{ cw_ldap_user }}",
    config_ldap_serv_password = "{{ cw_ldap_pass | b64encode }}",
    config_ldap_user_object = "{{ cw_ldap_filter_user_object }}",
    config_ldap_dn = "{{ cw_ldap_base }}",
    config_ldap_openldap = 1,
    config_ldap_group_object_filter = "{{ cw_ldap_filter_group_object }}",
    config_ldap_group_members_field = "bsdUID",
    config_ldap_group_name = "homelab"
    WHERE id = 1;'
  become: true
  become_user: _calibre-web-runner
