---
- name: install calibre-web packages
  package:
    name: '{{ cw_packages }}'
    state: present

- name: create calibre-web group
  group:
    name: _calibre

- name: create calibre-web user
  user:
    name: _calibre
    group: _calibre
    comment: Calibre Web user
    groups: ''
    home: /var/calibre
    login_class: daemon
    shell: /sbin/nologin
    password_lock: true
    password: '*************'

- name: remove calibre-web .ssh directory
  file:
    state: absent
    path: /var/calibre/.ssh

- name: create calibre-web virtualenv directory
  file:
    state: directory
    path: /var/calibre/cw_virtualenv
    owner: _homelab
    group: _homelab
    mode: '0755'

- name: install calibre-web in virtualenv
  pip:
    virtualenv: /var/calibre/cw_virtualenv
    name: 'calibreweb[ldap]'
  environment:
    CPPFLAGS: '-I/usr/local/include'
    LDFLAGS: '-L/usr/local/lib'
    HOME: /var/calibre/cw_virtualenv
  become: true
  become_user: _homelab

- name: install calibre-web launcher
  copy:
    src: calibre_web-launcher
    dest: /usr/local/libexec/calibre_web-launcher
    owner: root
    group: wheel
    mode: '0755'

- name: create calibre-web rc script
  template:
    src: calibre_web.j2
    dest: /etc/rc.d/calibre_web
    owner: root
    group: wheel
    mode: '0755'

#- name: enable calibre-web service
#  service:
#    name: calibre_web
#    enabled: true
#    state: started

- name: set config options in calibre-web sqlite db
  command: >
    sqlite3 /var/calibre/.calibre-web/app.db
    'UPDATE settings SET
    mail_server = "{{ cw_smtp_host }}",
    mail_port = "{{ cw_smtp_port }}",
    mail_use_ssl = {{ 2 if cw_smtp_tls else 1 if cw_smtp_starttls else 0 }},
    mail_login = "{{ cw_smtp_user }}",
    mail_password = "{{ cw_smtp_pass }}",
    mail_from = "{{ cw_smtp_from }}",
    config_calibre_dir = "/var/calibre/books",
    config_login_type = 1,
    config_ldap_provider_url = "127.0.0.1",
    config_ldap_port = 389,
    config_ldap_authentication = 2,
    config_ldap_serv_username = "{{ cw_ldap_user }}",
    config_ldap_serv_password = "{{ cw_ldap_pass | b64encode }}",
    config_ldap_user_object = "mail=%s",
    config_ldap_dn = "{{ cw_ldap_base }}",
    config_ldap_openldap = 1,
    config_ldap_group_object_filter = "(&(objectClass=hlApplication)(hlAppName=%s))",
    config_ldap_group_members_field = "member",
    config_ldap_group_name = "calibre"
    WHERE id = 1;'
  become: true
  become_user: _calibre
