---
- name: sysctl semmni  # noqa name[casing]
  ansible.builtin.command: sysctl kern.seminfo.semmni={{ psql_semmni }}

- name: sysctl semmns  # noqa name[casing]
  ansible.builtin.command: sysctl kern.seminfo.semmns={{ psql_semmns }}

- name: restart postgresql  # noqa name[casing]
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: restarted
