---
php_version: '7.4'

php_extensions:
  - 'php'
  - 'php-gd'
  - 'php-pgsql'
  - 'php-curl'
  - 'php-pdo_pgsql'
  - 'php-imap'
  - 'php-ldap'
  - 'php-zip'

php_extra_packages:
  - "pecl{{ php_version | replace('.', '') }}-redis"
